O_TARGET := data.o

obj-y	:=  Deal_Handler.o Task_Server_Comm.o iso8583.o Time_Utity.o md5.o des.o param.o file.o globalvar.o uart.o qt.o  interface_meter.o \
          MC.o  MC_can.o  Billing_system_dc.o \
					ic.o AC_meter_645_2007.o  meter_645_1997.o DC_meter_645_2007.o \
			Led_Control.o	warn.o  crc32.o  InDTU332W_Driver.o AC_Col_Interface.o  common.o Ftp_task.o tcp_modbus.o Power_Proces_Task.o Allocation_Power.o 


include $(TOPDIR)/Rules.make
