O_TARGET := data.o

obj-y	:=  md5.o des.o param.o file.o globalvar.o uart.o qt1.o qt2.o MC1.o MC2.o MC_can1.o MC_can2.o ic.o iso8583.o meter_645_1997.o DC_meter_645_2007.o AC_meter_645_2007.o warn1.o warn2.o \
          crc32.o InDTU332W_Driver.o common.o Led_Control.o 

include $(TOPDIR)/Rules.make
